name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
    tags:
      - 'v*'   # Publica para tags tipo v0.1.0, v0.2.0

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image tags
        run: |
          TAGS=""
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAGS="main latest"
          elif [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
            TAGS="development"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="$VERSION latest"
          else
            TAGS="latest"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          echo "Docker image will be tagged as: $TAGS"

      - name: Build Docker image
        run: |
          # Build once with the first tag in the list
          FIRST_TAG=$(echo $TAGS | awk '{print $1}')
          IMAGE=ghcr.io/${GITHUB_REPOSITORY}/wildintel-tools:$FIRST_TAG
          echo "Building $IMAGE"
          docker build -t $IMAGE .

          # Tag the image with the remaining tags
          for TAG in $TAGS; do
            if [ "$TAG" != "$FIRST_TAG" ]; then
              docker tag $IMAGE ghcr.io/${GITHUB_REPOSITORY}/wildintel-tools:$TAG
              echo "Tagged $TAG"
            fi
          done

      - name: Push Docker images
        run: |
          for TAG in $TAGS; do
            IMAGE=ghcr.io/${GITHUB_REPOSITORY}/wildintel-tools:$TAG
            echo "Pushing $IMAGE"
            docker push $IMAGE
          done
